# Generated by Django 2.0.6 on 2018-08-11 12:44

from django.db import migrations, models
import django.db.models.deletion
import tagging.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp - created')),
                ('changed', models.DateTimeField(auto_now=True, help_text='Timestamp - last changed')),
                ('title', models.CharField(help_text='Title of the Page', max_length=75)),
                ('slug', models.SlugField(help_text='Slug used in URL', unique=True)),
                ('featured', models.BooleanField(default=False, help_text='Should it appear on the navigation bar?')),
                ('footer', models.BooleanField(default=False, help_text='Should it appear in the footer?')),
                ('tags', tagging.fields.TagField(blank=True, help_text='List of Tags', max_length=255)),
                ('meta_keywords', models.TextField(blank=True, help_text='Keywords for meta tag.', null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Description for meta tag and children listing.', null=True)),
                ('body', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp - created')),
                ('changed', models.DateTimeField(auto_now=True, help_text='Timestamp - last changed')),
                ('title', models.CharField(help_text='Title of the Page', max_length=75)),
                ('slug', models.SlugField(help_text='Slug used in URL', unique=True)),
                ('featured', models.BooleanField(default=False, help_text='Should it appear on the navigation bar?')),
                ('footer', models.BooleanField(default=False, help_text='Should it appear in the footer?')),
                ('tags', tagging.fields.TagField(blank=True, help_text='List of Tags', max_length=255)),
                ('meta_keywords', models.TextField(blank=True, help_text='Keywords for meta tag.', null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Description for meta tag and children listing.', null=True)),
                ('body', tinymce.models.HTMLField(help_text='Content of the Page')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent Page', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children_set', to='anw.Page')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
