# Generated by Django 2.0.6 on 2018-06-17 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anw', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='title_slug',
            new_name='slug',
        ),
    ]
