# Generated by Django 3.2rc1 on 2021-03-26 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Verbose name', max_length=64, unique=True)),
                ('slug', models.SlugField(help_text='Unique URL identifier', max_length=64, unique=True)),
                ('description', models.CharField(blank=True, help_text='Short description', max_length=255)),
                ('attributes', models.JSONField(blank=True, help_text='Additional HTML attributes', null=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Generic parent tag', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tagging.tag')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(db_index=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagging.tag')),
            ],
            options={
                'ordering': ('tag', 'content_type', 'object_id'),
                'unique_together': {('tag', 'content_type', 'object_id')},
            },
        ),
    ]
