"""
Django settings for aintnowiki project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!mw9k=-2t(j32su@fcmz6^@)udmx0nokgofs4j#g!t#-41id3h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'filebrowser',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tinymce',
    'tagging',
    'bootstrap4',
    'sorl.thumbnail',
    'anw',
    'multitag'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'aintnowiki.urls'

TEMPLATES = [
    {
        'BACKEND':  'django.template.backends.django.DjangoTemplates',
        'DIRS':     [],
        'APP_DIRS': True,
        'OPTIONS':  {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aintnowiki.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME':   os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

# TinyMCE config
TINYMCE_DEFAULT_CONFIG = {
    'plugins':                           "autolink,lists,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",
    'theme':                             "advanced",
    'theme_advanced_toolbar_location':   "top",
    'theme_advanced_toolbar_align':      "left",
    'theme_advanced_statusbar_location': "bottom",
    'theme_advanced_buttons1':           "bold,italic,underline,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,attribs,styleprops",
    'theme_advanced_buttons2':           "fontselect,fontsizeselect,|,tablecontrols,",
    'theme_advanced_buttons3':           "cut,copy,paste,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,",
    'theme_advanced_buttons4':           "visualchars,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,preview,fullscreen,code,spellchecker",
    'theme_advanced_resizing':           'true',
    'skin':                              "o2k7",
    'skin_variant':                      "silver",
    'body_id':                           "pages_body",
    'body_class':                        "pages_body",
    'width':                             "100%",
    'height':                            "30em",
    'content_css':                       "https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css",
    # 'content_css': MEDIA_URL + "themes/"+ WIKI_THEME +"/css/theme.css" ,
    'relative_urls':                     False,
    'preformatted':                      'true',
    'verify_html':                       'false',
    # 'file_browser_callback': 'CustomFileBrowser'
}

MEDIA_ROOT = BASE_DIR
MEDIA_URL = "/media/"
FILEBROWSER_SAVE_FULL_URL = True

ANW_HOMEPAGE = "home"
ANW_NUM_CARDS = 3

# This option is required by filebrowser/sorl
TEMPLATE_DEBUG = DEBUG
