# Generated by Django 3.2rc1 on 2021-03-22 09:12

from django.db import migrations, models
import tagging.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Page title', max_length=255)),
                ('slug', models.SlugField(help_text='Unique URL identifier', max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('changed', models.DateTimeField(auto_now=True, help_text='Last change')),
                ('summary', models.TextField(help_text='Short summary to show in listing')),
                ('content', models.TextField(help_text='Page content')),
            ],
            options={
                'ordering': ('-changed',),
            },
            bases=(tagging.mixins.TaggedMixin, models.Model),
        ),
    ]
