# Generated by Django 3.2rc1 on 2021-06-27 08:01
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
        migrations.RunSQL(
            sql="CREATE INDEX trgm_slug_idx ON wiki_page USING GIN (slug gin_trgm_ops)",
            reverse_sql=migrations.RunSQL.noop
        )
    ]
